# Generated by Django 5.1.2 on 2024-10-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_alter_msauthlink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msauthlink',
            name='key',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='msauthlink',
            name='refresh_key',
            field=models.CharField(max_length=3000),
        ),
    ]
