# Generated by Django 5.1.2 on 2024-10-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0004_alter_msauthlink_key_alter_msauthlink_refresh_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='msauthlink',
            name='temp_token',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
