# Generated by Django 5.1.2 on 2024-10-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0005_msauthlink_temp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='msauthlink',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
